find_path(SYMPHONY_INCLUDE_DIR coin/symphony.h)
find_library(SYMPHONY_LIBRARY Sym)
set(SYMPHONY_FOUND "NO")

if(SYMPHONY_INCLUDE_DIR AND SYMPHONY_LIBRARY)
    set(SYMPHONY_FOUND "YES")
endif(SYMPHONY_INCLUDE_DIR AND SYMPHONY_LIBRARY)
