#ifndef __PAMAURY_CONFIG_HPP__
#define __PAMAURY_CONFIG_HPP__

#define PAMAURY_SCHEDULER_NS    pasched

#cmakedefine HAS_SYMHPONY
#cmakedefine ENABLE_DAG_AUTO_CHECK_CONSISTENCY
#cmakedefine ENABLE_SCHED_AUTO_CHECK_RP
#cmakedefine ENABLE_EXPENSIVE_SCHED_AUTO_CHECK_RP
#cmakedefine ENABLE_XFORM_AUTO_CHECK_RP
#cmakedefine ENABLE_XFORM_TIME_STAT

#endif // __PAMAURY_CONFIG_HPP__
